language: python

python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - flake8 stones
  - pytest -ra -sv --cov=stones tests/

after_success:
  - codecov

branches:
  only:
    - master
