language: python
sudo: false

python:
  - 3.6
  - 3.7

install:
  - make update

script:
  - make lint
  - pytest -ra -sv --cov=stones tests/

after_success:
  - codecov

branches:
  only:
    - master
